#!/usr/bin/env bash
set -euo pipefail #bash-safety-flags

STOWDIR="$(dirname $(realpath $0))/system"
STOWTARGET=/

cd $STOWDIR
echo $STOWDIR "->" $STOWTARGET

for dir in */; do
    pkg="${dir%/}"
    echo ""
    echo $pkg
    sudo stow --restow $pkg --target=$STOWTARGET --verbose=1 

sudo udevadm control --reload-rules
sudo systemctl daemon-reload
done