#!/usr/bin/env bash
set -euo pipefail #Bash-Safety-Flags

EXCLUDE="displaylink"  # space-separated, e.g. "displaylink vlc"

cd "$HOME/git/.dotfiles"

for dir in */; do
    pkg="${dir%/}"
    [[ " $EXCLUDE " == *" $pkg "* ]] && continue
    stow -R "$pkg"
done
