# sddm (Simple Desktop Display Manager) configuration
[General]
DisplayServer=wayland
Numlock=on

[Wayland]
SessionDir="/usr/local/share/wayland-sessions,/usr/share/wayland-sessions" #default

[Users]
RememberLastSession=true #default